#!/bin/bash
set -euo pipefail

rm -rf build
mkdir build

cd ./src
zip -r ../build/epa-zotero-plugin-1.0.xpi *
cd ../build


jq ".addons[\"github@epa.gov\"].updates[0].update_hash = \"sha256:`shasum -a 256 epa-zotero-plugin-1.0.xpi | cut -d' ' -f1`\"" ../updates-1.0.json.tmpl > updates-1.0.json
