#!/bin/bash
set -euo pipefail

XPI_FILENAME="epa-zotero-plugin@epa.gov.xpi"
TMPL_FILENAME="updates.json.tmpl"
UPDATES_FILENAME="updates.json"

rm -rf build
mkdir build

cd ./src
if command -v zip &>/dev/null; then
    zip -r "../build/$XPI_FILENAME" *
else
    7z a -tzip -mx=9 "../build/$XPI_FILENAME" *
fi
cd ../build

XPI_HASH=$(shasum -a 256 "$XPI_FILENAME" | cut -d' ' -f1)
GIT_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0")

jq ".addons[\"epa-zotero-plugin@epa.gov\"].updates[0] |= (.update_hash = \"sha256:$XPI_HASH\" | .version = \"$GIT_TAG\")" \
    "../$TMPL_FILENAME" > $UPDATES_FILENAME
