#!/bin/bash
set -euo pipefail

XPI_FILENAME="epa-zotero-plugin@epa.gov.xpi"
TMPL_FILENAME="updates.json.tmpl"
UPDATES_FILENAME="updates.json"
GIT_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0")
BASE_URL="$(jq -r ".homepage_url" ./src/manifest.json)"

jq ".version = \"$GIT_TAG\"" ./src/manifest.json > ./src/manifest.json.tmp
mv ./src/manifest.json.tmp ./src/manifest.json

rm -rf build
mkdir build

cd ./src
if command -v zip &>/dev/null; then
    zip -r "../build/$XPI_FILENAME" *
else
    7z a -tzip -mx=9 "../build/$XPI_FILENAME" *
fi
cd ..

XPI_HASH=$(shasum -a 256 "./build/$XPI_FILENAME" | cut -d' ' -f1)
UPDATE_LINK="$BASE_URL/releases/download/$GIT_TAG/$XPI_FILENAME"

jq ".addons[\"epa-zotero-plugin@epa.gov\"].updates[0] |= (.update_hash = \"sha256:$XPI_HASH\" | .version = \"$GIT_TAG\" | .update_link = \"$UPDATE_LINK\")" $TMPL_FILENAME > ./build/$UPDATES_FILENAME
